apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tocpay-1-mowf
  namespace: personal-automation
spec:
  schedule: "05 18 1,3,5,7,9,11,13,15,17,19 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: tocpay
            image: town_of_cary_payment:20.04
            command:
              - python3
              - "/root/tocpay/town_of_cary_payment.py"
              - "--amount"
              - "1.00"
              - "--card-label"
              - "11603072"
            imagePullPolicy: Never
          restartPolicy: OnFailure
