apiVersion: batch/v1
kind: Job
metadata:
  name: tocpay-1-mowf
  namespace: personal-automation
spec:
  template:
    spec:
      containers:
      - name: tocpay
        image: town_of_cary_payment:20.04
        command:
          - python3
          - "/root/tocpay/town_of_cary_payment.py"
          - "--amount"
          - "1.00"
          - "--card-label"
          - "11603072"
        imagePullPolicy: Never
      restartPolicy: OnFailure
